# Generated by Django 3.1.7 on 2021-02-20 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GroupOfUser',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserOfGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('user_category', models.ManyToManyField(through='mainapp.GroupAndUser', to='mainapp.GroupOfUser')),
            ],
        ),
        migrations.AddField(
            model_name='groupofuser',
            name='users',
            field=models.ManyToManyField(through='mainapp.GroupAndUser', to='mainapp.UserOfGroup'),
        ),
        migrations.AddField(
            model_name='groupanduser',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.userofgroup'),
        ),
        migrations.AddField(
            model_name='groupanduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.groupofuser'),
        ),
    ]
