# Generated by Django 3.1.7 on 2021-02-20 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupanduser',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.groupofuser'),
        ),
        migrations.AlterField(
            model_name='groupanduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.userofgroup'),
        ),
    ]
